- name: Add repository with recent GPU drivers
  apt_repository:
    repo: ppa:graphics-drivers/ppa
    state: present

- name: Include os version-specific vars 
  include_vars: "{{ ansible_distribution_release }}.yml"

- name: Check if required package version is already present
  shell: dpkg --get-selections | grep {{driver_package_names_install[0]}} | wc -l
  register: nvidia_driver_need_remove 

- name: Remove old NVIDIA driver
  apt:
    pkg: "{{driver_package_names_remove}}"
    state: absent
    purge: yes
    autoremove: yes
  when: nvidia_driver_need_remove.stdout == "0"

- name: Install NVIDIA driver and utils
  apt:
    pkg: "{{ driver_package_names_install }}"
    state: present
    update_cache: yes
    autoremove: yes