- name: Add repository with recent GPU drivers
  apt_repository:
    repo: ppa:graphics-drivers/ppa
    state: present

- name: Check if required package version is already present
  shell: dpkg --get-selections | grep {{nvidia_driver_package_name}} | wc -l
  register: package_state 

- name: Remove old NVIDIA driver
  apt:
    pkg:
        - nvidia-driver*
        - nvidia-3*
    state: absent
    purge: yes
    autoremove: yes
  when: package_state.stdout == "0"

- name: Install NVIDIA driver and utils
  apt:
    pkg: 
        - "{{nvidia_driver_package_name }}"
        - "nvidia-utils-{{driver_version}}"
    state: present
    update_cache: yes
    autoremove: yes